"""
SIH 2026 - Robust Digital Demodulator

Supports the modulation schemes currently generated by
dataset_generator.py:

    BPSK
    QPSK
    8PSK
    16QAM

The modulation type is NOT hardcoded by the pipeline.
It is supplied by the ML classifier.

Receiver flow:

    Noisy IQ
        ↓
    Symbol averaging
        ↓
    Modulation-specific demodulation
        ↓
    Coded/interleaved bits
"""


import numpy as np


# ============================================================
# CONFIGURATION
# ============================================================

DEFAULT_SAMPLES_PER_SYMBOL = 100


# ============================================================
# SYMBOL EXTRACTION
# ============================================================

def extract_symbols(
    iq_samples,
    samples_per_symbol: int = DEFAULT_SAMPLES_PER_SYMBOL
) -> np.ndarray:
    """
    Convert oversampled IQ data into one complex value
    per transmitted symbol.

    The generator repeats every symbol 100 times.

    Instead of making 100 separate decisions, we average
    the 100 noisy samples into one symbol estimate.

    This improves robustness against AWGN noise.
    """

    samples = np.asarray(
        iq_samples,
        dtype=np.complex64
    )

    if samples.size == 0:
        return np.array(
            [],
            dtype=np.complex64
        )

    samples_per_symbol = max(
        1,
        int(samples_per_symbol)
    )

    usable_length = (
        len(samples)
        // samples_per_symbol
    ) * samples_per_symbol

    if usable_length == 0:
        return np.array(
            [],
            dtype=np.complex64
        )

    samples = samples[
        :usable_length
    ]

    blocks = samples.reshape(
        -1,
        samples_per_symbol
    )

    # Average each block.
    symbols = np.mean(
        blocks,
        axis=1
    )

    return symbols


# ============================================================
# BPSK
# ============================================================

def demodulate_bpsk(
    symbols: np.ndarray
) -> str:
    """
    BPSK mapping used by the generator:

        0 → -1
        1 → +1

    Decision is based on the real component.
    """

    bits = [
        "1" if symbol.real >= 0
        else "0"
        for symbol in symbols
    ]

    return "".join(bits)


# ============================================================
# QPSK
# ============================================================

def demodulate_qpsk(
    symbols: np.ndarray
) -> str:
    """
    QPSK mapping used by the generator:

        00 → (-I, -Q)
        01 → (-I, +Q)
        10 → (+I, -Q)
        11 → (+I, +Q)

    Therefore:
        real < 0 → first bit 0
        real >= 0 → first bit 1

        imag < 0 → second bit 0
        imag >= 0 → second bit 1
    """

    bits = []

    for symbol in symbols:

        first_bit = (
            "1"
            if symbol.real >= 0
            else "0"
        )

        second_bit = (
            "1"
            if symbol.imag >= 0
            else "0"
        )

        bits.extend(
            [
                first_bit,
                second_bit
            ]
        )

    return "".join(bits)


# ============================================================
# 8-PSK
# ============================================================

def demodulate_8psk(
    symbols: np.ndarray
) -> str:
    """
    8PSK mapping used by the generator:

        value = b1*4 + b2*2 + b3

        phase = 2*pi*value/8

    The nearest phase determines the 3-bit value.
    """

    bits = []

    for symbol in symbols:

        phase = np.angle(symbol)

        # Convert phase from:
        #
        #     [-pi, pi]
        #
        # to:
        #
        #     [0, 2*pi)
        #

        if phase < 0:
            phase += 2 * np.pi

        # Find nearest of 8 phase positions.
        symbol_index = int(
            np.round(
                phase
                / (2 * np.pi / 8)
            )
        ) % 8

        # Convert 0..7 into 3 bits.
        bit_group = format(
            symbol_index,
            "03b"
        )

        bits.extend(bit_group)

    return "".join(bits)


# ============================================================
# 16-QAM
# ============================================================

def demodulate_16qam(
    symbols: np.ndarray
) -> str:
    """
    16QAM mapping used by the generator:

        00 → -3
        01 → -1
        11 → +1
        10 → +3

    The I and Q components are independently mapped
    to their nearest amplitude level.
    """

    levels = np.array(
        [-3, -1, 1, 3],
        dtype=float
    )

    bit_mapping = {
        -3: "00",
        -1: "01",
        1: "11",
        3: "10"
    }

    bits = []

    # The generator normalizes by sqrt(10).
    # Convert received normalized amplitude back
    # to the original level scale.
    scale = np.sqrt(10)

    for symbol in symbols:

        i_value = (
            symbol.real * scale
        )

        q_value = (
            symbol.imag * scale
        )

        # Find nearest I level.
        i_level = levels[
            np.argmin(
                np.abs(
                    levels - i_value
                )
            )
        ]

        # Find nearest Q level.
        q_level = levels[
            np.argmin(
                np.abs(
                    levels - q_value
                )
            )
        ]

        bits.extend(
            bit_mapping[int(i_level)]
        )

        bits.extend(
            bit_mapping[int(q_level)]
        )

    return "".join(bits)


# ============================================================
# MAIN DEMODULATOR
# ============================================================

def demodulate_symbols(
    iq_samples,
    modulation_type: str,
    samples_per_symbol: int = DEFAULT_SAMPLES_PER_SYMBOL
) -> str:
    """
    Main modulation-aware demodulator.

    IMPORTANT:
        modulation_type is supplied by the classifier.

    It is NOT hardcoded.

    Supported names:

        BPSK
        QPSK
        8PSK
        8-PSK
        16QAM
        16-QAM
    """

    if iq_samples is None:

        return ""

    # --------------------------------------------------------
    # Extract one symbol from each block.
    # --------------------------------------------------------

    symbols = extract_symbols(
        iq_samples,
        samples_per_symbol
    )

    if len(symbols) == 0:

        return ""

    # --------------------------------------------------------
    # Normalize modulation name.
    #
    # The classifier uses "8-PSK" and "16-QAM",
    # while the generator uses "8PSK" and "16QAM".
    # --------------------------------------------------------

    normalized_type = (
        str(modulation_type)
        .strip()
        .upper()
        .replace("-", "")
        .replace("_", "")
        .replace(" ", "")
    )

    # --------------------------------------------------------
    # Select demodulator.
    # --------------------------------------------------------

    if normalized_type == "BPSK":

        return demodulate_bpsk(
            symbols
        )

    if normalized_type == "QPSK":

        return demodulate_qpsk(
            symbols
        )

    if normalized_type == "8PSK":

        return demodulate_8psk(
            symbols
        )

    if normalized_type == "16QAM":

        return demodulate_16qam(
            symbols
        )

    raise ValueError(
        f"Unsupported modulation type: "
        f"{modulation_type}"
    )


# ============================================================
# SIMPLE SELF-TESTS
# ============================================================

def test_bpsk():

    original = "10110010"

    # Generate ideal BPSK symbols.
    symbols = np.array(
        [
            1 if bit == "1"
            else -1
            for bit in original
        ],
        dtype=np.complex64
    )

    # Repeat each symbol 100 times,
    # just like dataset_generator.py.
    iq = np.repeat(
        symbols,
        DEFAULT_SAMPLES_PER_SYMBOL
    )

    decoded = demodulate_symbols(
        iq,
        "BPSK"
    )

    assert decoded == original

    print(
        "✅ BPSK test passed"
    )


def test_qpsk():

    original = "10110010"

    symbols = []

    for i in range(
        0,
        len(original),
        2
    ):

        first = int(
            original[i]
        )

        second = int(
            original[i + 1]
        )

        i_value = (
            2 * first - 1
        )

        q_value = (
            2 * second - 1
        )

        symbols.append(
            (
                i_value
                + 1j * q_value
            )
            / np.sqrt(2)
        )

    symbols = np.array(
        symbols,
        dtype=np.complex64
    )

    iq = np.repeat(
        symbols,
        DEFAULT_SAMPLES_PER_SYMBOL
    )

    decoded = demodulate_symbols(
        iq,
        "QPSK"
    )

    assert decoded == original

    print(
        "✅ QPSK test passed"
    )


def test_8psk():

    original = "101100"

    symbols = []

    for i in range(
        0,
        len(original),
        3
    ):

        value = int(
            original[i:i + 3],
            2
        )

        phase = (
            2 * np.pi * value / 8
        )

        symbols.append(
            np.exp(1j * phase)
        )

    symbols = np.array(
        symbols,
        dtype=np.complex64
    )

    iq = np.repeat(
        symbols,
        DEFAULT_SAMPLES_PER_SYMBOL
    )

    decoded = demodulate_symbols(
        iq,
        "8-PSK"
    )

    assert decoded == original

    print(
        "✅ 8PSK test passed"
    )


def test_16qam():

    original = "10110010"

    mapping = {
        (0, 0): -3,
        (0, 1): -1,
        (1, 1): 1,
        (1, 0): 3
    }

    symbols = []

    for i in range(
        0,
        len(original),
        4
    ):

        i_value = mapping[
            (
                int(original[i]),
                int(original[i + 1])
            )
        ]

        q_value = mapping[
            (
                int(original[i + 2]),
                int(original[i + 3])
            )
        ]

        symbols.append(
            (
                i_value
                + 1j * q_value
            )
            / np.sqrt(10)
        )

    symbols = np.array(
        symbols,
        dtype=np.complex64
    )

    iq = np.repeat(
        symbols,
        DEFAULT_SAMPLES_PER_SYMBOL
    )

    decoded = demodulate_symbols(
        iq,
        "16-QAM"
    )

    assert decoded == original

    print(
        "✅ 16QAM test passed"
    )


# ============================================================
# RUN TESTS
# ============================================================

if __name__ == "__main__":

    print("=" * 60)
    print("ROBUST DEMODULATOR TEST")
    print("=" * 60)

    test_bpsk()
    test_qpsk()
    test_8psk()
    test_16qam()

    print()
    print(
        "✅ ALL DEMODULATOR TESTS PASSED"
    )