"""
SIH 2026 - Demodulation + Classifier Integration

Connects:

    IQ Signal
        ↓
    ML Modulation Classifier
        ↓
    Modulation Type + Confidence
        ↓
    Robust Demodulator
        ↓
    Demodulated Bits

The modulation type is obtained dynamically from
the classifier and is NOT hardcoded.
"""

from pathlib import Path

import numpy as np

from param_estimation.modulation_classifier import (
    ModulationClassifier
)

from demodulation.robust_demodulator import (
    demodulate_symbols
)

from deinterleave_fec.bitstream_correlation import (
    BitstreamCorrelator,
    FrameParser,
)

from deinterleave_fec.fec_decoder import (
    deinterleave_bits,
    hamming_7_4_decode_bits,
    viterbi_decode,
    bits_to_ascii,
)

# ============================================================
# CONFIGURATION
# ============================================================

SAMPLES_PER_SYMBOL = 100

SYNC_WORD = "10101011"


# ============================================================
# IQ LOADING
# ============================================================

def load_iq_file(
    file_path
) -> np.ndarray:
    """
    Load a complex64 IQ file generated by
    dataset_generator.py.
    """

    path = Path(file_path)

    if not path.exists():

        raise FileNotFoundError(
            f"IQ file not found: {path}"
        )

    iq_samples = np.fromfile(
        path,
        dtype=np.complex64
    )

    return iq_samples


# ============================================================
# CLASSIFICATION + DEMODULATION
# ============================================================

def classify_and_demodulate(
    iq_samples: np.ndarray,
    classifier: ModulationClassifier
) -> dict:
    """
    Run the ML classifier first.

    The classifier returns:

        modulation_type
        confidence

    That modulation type is then passed directly
    to the demodulator.

    Nothing is hardcoded here.
    """

    # --------------------------------------------------------
    # Step 1:
    # Ask the ML classifier what modulation is present.
    # --------------------------------------------------------

    modulation_type, confidence = (
        classifier.classify(
            iq_samples
        )
    )

    # --------------------------------------------------------
    # Step 2:
    # Pass the classifier's modulation type directly
    # to the demodulator.
    # --------------------------------------------------------

    demodulated_bits = (
        demodulate_symbols(
            iq_samples,
            modulation_type,
            samples_per_symbol=SAMPLES_PER_SYMBOL
        )
    )

    return {
        "bits": demodulated_bits,
        "modulation_type": str(
            modulation_type
        ),
        "confidence": float(
            confidence
        )
    }


# ============================================================
# SYNC WORD HANDLING
# ============================================================

def remove_sync_word(
    bit_string: str
) -> str:
    """





    
    Remove the synchronization word using real cross-correlation.
    Autonomously discovers the boundary even in presence of noise or phase ambiguity.
    """
    correlator = BitstreamCorrelator(default_sync_pattern=SYNC_WORD, confidence_threshold=0.75)
    corr_res = correlator.correlate(bit_string)
    if corr_res.found:
        parser = FrameParser(header_length_bits=0)
        frame = parser.split_frame(bit_string, corr_res, auto_invert=True)
        return frame["payload_bits"]

    # Fallback to direct slice if starts with sync word
    if bit_string.startswith(SYNC_WORD):
        return bit_string[len(SYNC_WORD):]

    return bit_string


# ============================================================
# COMPLETE CLASSIFIER + DEMODULATION PIPELINE
# ============================================================

def process_iq_file(
    file_path,
    classifier: ModulationClassifier
) -> dict:
    """
    Load one IQ file and run:

        IQ
        ↓
        Classifier
        ↓
        Demodulator

    FEC decoding is intentionally NOT performed here yet.
    """

    iq_samples = load_iq_file(
        file_path
    )

    result = classify_and_demodulate(
        iq_samples,
        classifier
    )

    return {
        "file_path": str(file_path),

        "modulation_type": (
            result["modulation_type"]
        ),

        "confidence": (
            result["confidence"]
        ),

        "demodulated_bits": (
            result["bits"]
        ),

        "demodulated_bit_count": (
            len(result["bits"])
        )
    }

def decode_fec_message(
    demodulated_bits: str,
    has_fec: bool = True,
    has_interleaving: bool = False,
    interleaver_cols: int = 8,
    fec_scheme: str = "auto"
) -> dict:
    """
    Convert demodulated coded bits into the original
    ASCII message.

    Receiver order:

        Demodulated bits
              ↓
        Real sync correlation / framing
              ↓
        De-interleave
              ↓
        FEC (Hamming or Viterbi)
              ↓
        ASCII
    """

    # --------------------------------------------------------
    # Step 1: Real sync correlation & boundary detection
    # --------------------------------------------------------

    payload_bits = remove_sync_word(
        demodulated_bits
    )

    print(
        f"  Bits after sync removal: "
        f"{len(payload_bits)}"
    )

    # --------------------------------------------------------
    # Step 2: De-interleave if required
    # --------------------------------------------------------

    if has_interleaving:

        print(
            "  De-interleaving: ENABLED"
        )

        payload_bits = deinterleave_bits(
            payload_bits,
            cols=interleaver_cols
        )

    else:

        print(
            "  De-interleaving: DISABLED"
        )

    # --------------------------------------------------------
    # Step 3: FEC decoding
    # --------------------------------------------------------

    if has_fec:
        # Determine scheme: Person A dataset uses Hamming(7,4)
        use_hamming = (fec_scheme == "hamming") or (
            fec_scheme == "auto" and (len(payload_bits) % 7 == 0 or len(payload_bits) in (98, 104, 105))
        )

        if use_hamming:
            print("  Hamming(7,4) FEC decoding: ENABLED")
            decoded_bits, err_count = hamming_7_4_decode_bits(
                payload_bits, original_length=56
            )
            print(f"  Corrected errors: {err_count}")
        else:
            print("  Viterbi FEC decoding: ENABLED")
            decoded_bits = viterbi_decode(
                payload_bits,
                terminate=True
            )

    else:

        print(
            "  FEC decoding: DISABLED"
        )

        decoded_bits = payload_bits

    # --------------------------------------------------------
    # Step 4: Convert bits to ASCII
    # --------------------------------------------------------

    usable_length = (
        len(decoded_bits) // 8
    ) * 8

    decoded_bits = decoded_bits[
        :usable_length
    ]

    if decoded_bits:

        message = bits_to_ascii(
            decoded_bits
        )

    else:

        message = ""

    return {
        "payload_bits": payload_bits,
        "decoded_bits": decoded_bits,
        "message": message
    }

# ============================================================
# SIMPLE TEST
# ============================================================

def test_complete_fec_pipeline():
    """
    Test the complete clean FEC receiver:

        IQ
         ↓
        ML classifier
         ↓
        modulation
         ↓
        demodulation
         ↓
        sync removal
         ↓
        de-interleaving
         ↓
        Viterbi
         ↓
        ASCII
    """

    dataset_dir = Path(
        "synthetic_dataset"
    )

    # --------------------------------------------------------
    # Select a clean BPSK signal with FEC enabled
    # and interleaving disabled.
    #
    # This is the simplest end-to-end FEC test.
    # --------------------------------------------------------

    candidate_files = list(
        dataset_dir.glob(
            "*BPSK*snr30dB*fec1*itr1*.iq"
        )
    )

    if not candidate_files:

        raise FileNotFoundError(
            "No clean BPSK FEC test signal found."
        )

    iq_file = candidate_files[0]

    print("=" * 60)
    print(
        "COMPLETE FEC RECEIVER TEST"
    )
    print("=" * 60)

    print(
        f"IQ file: {iq_file.name}"
    )

    # --------------------------------------------------------
    # Load classifier
    # --------------------------------------------------------

    classifier = ModulationClassifier()

    # --------------------------------------------------------
    # Run classifier + demodulator
    # --------------------------------------------------------

    result = process_iq_file(
        iq_file,
        classifier
    )

    print()
    print(
        "CLASSIFIER"
    )

    print(
        f"  Detected modulation: "
        f"{result['modulation_type']}"
    )

    print(
        f"  Confidence: "
        f"{result['confidence']:.4f}"
    )

    print()
    print(
        "DEMODULATOR"
    )

    print(
        f"  Demodulated bits: "
        f"{result['demodulated_bit_count']}"
    )

    # --------------------------------------------------------
    # FEC decoding
    # --------------------------------------------------------

    print()
    print(
        "FEC DECODER"
    )

    decoded = decode_fec_message(
    result["demodulated_bits"],
    has_fec=True,
    has_interleaving=True
)

    print()
    print(
        f"  Decoded bits: "
        f"{len(decoded['decoded_bits'])}"
    )

    print(
        f"  ASCII message: "
        f"{decoded['message']!r}"
    )

    print()

    if decoded["message"] == "SIH2026":

        print(
            "[PASS] COMPLETE FEC PIPELINE PASSED: Recovered 'SIH2026'"
        )

    else:

        raise AssertionError(
            f"FEC pipeline did not recover 'SIH2026', got {decoded['message']!r}"
        )

    # --------------------------------------------------------
    # Load trained classifier.
    # --------------------------------------------------------

    classifier = ModulationClassifier()

    # --------------------------------------------------------
    # Run complete classifier → demodulator flow.
    # --------------------------------------------------------

    result = process_iq_file(
        iq_file,
        classifier
    )

    print()
    print(
        "Classifier result:"
    )

    print(
        f"  Modulation: "
        f"{result['modulation_type']}"
    )

    print(
        f"  Confidence: "
        f"{result['confidence']:.4f}"
    )

    print()
    print(
        "Demodulator result:"
    )

    print(
        f"  Recovered bits: "
        f"{result['demodulated_bit_count']}"
    )

    print()

    # --------------------------------------------------------
    # Verify that the classifier supplied a modulation
    # type to the demodulator.
    # --------------------------------------------------------

    if result["modulation_type"]:

        print(
            "[PASS] CLASSIFIER -> DEMODULATOR "
            "INTEGRATION PASSED"
        )

    else:

        raise AssertionError(
            "Classifier did not return "
            "a modulation type."
        )


# ============================================================
# PROGRAM ENTRY POINT
# ============================================================

if __name__ == "__main__":

    test_complete_fec_pipeline()
